apiVersion: v1 
kind: Deployment 
metadata: 
  name: app1 
  labels: 
    app: app1 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: app1 
  template: 
    metadata: 
      labels: 
        app: app1 
    spec: 
      containers: 
      - name: app1 
        image: trinathr/app1:1.0.0 
        ports: 
        - containerPort: 80 

--- 
apiVersion: v1 
kind: Service  
metadata: 
  name: app1
spec: 
  selector: 
    app: app1 
  ports: 
    port: 80 
    targetPort: 80 
    